# Generated by Django 3.0.7 on 2020-10-02 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=225)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designathon.Student')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='', max_length=225)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designathon.Organisation')),
            ],
        ),
    ]
