# Generated by Django 3.0.7 on 2020-10-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designathon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=225)),
                ('phn_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlacementsOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_name', models.CharField(max_length=225)),
                ('phn_no', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='clg_name',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phn_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
