# Generated by Django 3.0.7 on 2020-10-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designathon', '0002_auto_20201006_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='phn_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='placementsoff',
            name='phn_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phn_no',
            field=models.BigIntegerField(),
        ),
    ]
